### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by jonathanKingston** [jonathanKingston/http-dns#1]
Hey @flodolo,
I added the new files we spoke about here but I didn't add any links to the explainer page.
I think we might have to change the text slightly in study.html from the addon descriptions used in the manifest because of this. I wasn't sure on the best way to do links within the text without using innerHtml.

The manifest place holders however did work as you coded them :+1:

**Comment by flodolo** [comment]
Great, I wasn't sure it would work.

Do we know when the page text will be finalized? Otherwise, should we go ahead and start with exposing the strings we have so far?

**Comment by flodolo** [comment]
> I wasn't sure on the best way to do links within the text without using innerHtml.

One possible way is to use a placeholder for the link in the main string, then build the DOM using the fragments. This code relies on the fact that placeholders are either `%S, %S, %S` or `%1$S, %2$S, etc.` in properties files
https://hg.mozilla.org/mozilla-central/file/default/toolkit/modules/BrowserUtils.jsm#l668

The string would like like this in .properties:

```properties
test = This is a {test}
```

Resulting in this JSON:

```JSON
  "test": {
    "message": "This is a $TEST$",
    "placeholders": {
      "test": {
        "content": "$1"
      }
    }
  }
```

**Comment by jonathanKingston** [comment]
Yeah this won't be possible, I can't cross DOM across the extension API boundary. I could inject it from the chrome scripts but it would require a lot of custom chrome code to do this. I think I'm just going to use DOMPurify so I can send you the content later today.

**Comment by jonathanKingston** [comment]
I added the updated translations to: https://github.com/jonathanKingston/http-dns/blob/master/src/_locales/en_US/messages.json which I think are final (We might want to double check with Michelle), feel free to modify them though.

The extension loads them into study.html but only permits `<a>` tags and `href` attributes via DOMPurify which should be sufficient for the risk here.

**Comment by flodolo** [comment]
Thanks, I'll start an email thread to confirm. At this point I won't be able to expose them before the weekend, but I'll do it first think next week, and slightly move the deadline.

**Comment by flodolo** [comment]
> I added the updated translations to: https://github.com/jonathanKingston/http-dns/blob/master/src/_locales/en_US/messages.json which I think are final (We might want to double check with Michelle), feel free to modify them though.

Just realized that the approach won't work, there's no way to localize the text used inside the link?

**Comment by flodolo** [comment]
> Just realized that the approach won't work, there's no way to localize the text used inside the link?

Actually, let me wrap my head around this and get back to you.

A few more notes:
* Remove double spaces after period.
* ~Link to SUMO should not include en-US, just `https://support.mozilla.org/kb/shield`.~ Should actually be `https://medium.com/@linclark/cee3af19f10a`
* There's a FIrefox
* Link "Series" should probably by "studies", lowercase? (confirmed by Michelle)
* Nightly Firefox -> Firefox Nightly?

I'll try to provide an updated JSON if I can figure it all out.

**Comment by flodolo** [comment]
@jonathanKingston 
Would you be able to work with something like this? Note that the JSON is quite different, and I've included the notes/changes from my previous comment.

You would have to pass the text of links to the main string, when calling `browser.i18n.getMessage`
https://gist.github.com/flodolo/e5705dd62de81bc393f0eb801350adba

**Comment by flodolo** [comment]
One more thought: if we ever want to use this content out of Nightly, we should get rid of hardcoded "Nightly" in all the strings.

I've create a temp repo to make it easier to look at diffs.
https://github.com/flodolo/temp_dns_test/commits/master/locales/en-US/experiment.properties

Pointing out some changes in particular
https://github.com/flodolo/temp_dns_test/commit/3f3b68d589c6eaa0859502fef6e02d14988181e7#diff-e2056f5bec11617b2794ecd72066a057

**Nightly Firefox** is not something I've seen before, it's always **Firefox Nightly**. There are a couple of strings in the original that use that form.

I believe that we should get rid of some *Nighly*, e.g.
* `We are running a series of studies in Nightly. All Nightly users…`. *All users* should be enough, without repeating *Nightly*?
* `To disable all studies in Nightly, you can update your…`. I think we can just say *Firefox* here, instead of Nightly?

@mheubusch
Thoughts?

**Comment by mheubusch** [comment]
Thanks, flod. Yes, Firefox Nightly is the correct term. Not sure how the reverse got in there. Also agree that we don’t need to restate Nightly per your first bullet point. If we change Nightly to Firefox per your second bullet, will the line remain true, ie does it opt you out of all Firefox studies for that profile or just on Nightly?

**Comment by flodolo** [comment]
> If we change Nightly to Firefox per your second bullet, will the line remain true, ie does it opt you out of all Firefox studies for that profile or just on Nightly?

I believe that changes a preference in your profile (`app.shield.optoutstudies.enabled`), so it would affect any version of Firefox running on the same profile.

@jonathanKingston 
At this point I mostly need confirmation that you can work with this [JSON file](https://github.com/flodolo/temp_dns_test/blob/master/_locales/en_US/messages.json).

**Comment by jonathanKingston** [comment]
I think all tasks here are done here right?

**Comment by flodolo** [comment]
Might want to keep it open until the content of the file is confirmed as final?

We also need the build steps on the add-on side to convert properties into JSON.

**Comment by flodolo** [comment]
This is what I'm [using to test](https://github.com/jonathanKingston/http-dns/compare/master...flodolo:l10n?expand=1), you probably want something cleaner ;-)

Tests for Italian look good

![schermata 2018-05-11 alle 09 38 48](https://user-images.githubusercontent.com/3644868/39912534-565fee22-54ff-11e8-8e20-04fa6f127c25.png)

![schermata 2018-05-11 alle 09 38 51](https://user-images.githubusercontent.com/3644868/39912541-5afaeff4-54ff-11e8-9831-352ff4de52f4.png)

**Comment by jonathanKingston** [comment]
@flodolo the only differences I would make are:
- Add other languages to `.gitignore` as they aren't the source of truth, so I think it makes sense not to check them in.
- add `npm run import-l10n` to the build command too.

Shall I make those and merge?

I'm also interested why the russian uses "Отключить исследование «DNS через HTTPS»"  is the bracket notation needed? Won't that break the button?

**Comment by flodolo** [comment]
> Add other languages to .gitignore as they aren't the source of truth, so I think it makes sense not to check them in.

I think it makes sense for them to be in the repository (in JSON format), because the version you tag would match the version you actually ship. It would be really hard to figure out "what shipped where" otherwise.

> add npm run import-l10n to the build command too.

You mean run it as part of "build"? That makes sense.

Feel free to take what you can use and merge ;-)

I'll check the Russian button, knowing the translation it's still incomplete. I don't think it would break the button though.

**Comment by flodolo** [comment]
> I'll check the Russian button, knowing the translation it's still incomplete. I don't think it would break the button though.

Awfully long, but not broken

![schermata 2018-05-11 alle 12 23 46](https://user-images.githubusercontent.com/3644868/39920109-32b1ec3e-5516-11e8-962b-f20fbe1596b3.png)
