### ISSUE TITLE
"network.trr.experimentalRollout" pref value doesn't change to -1 when removing the experiment from "about:addons" page

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [jonathanKingston/http-dns#10]
**[Affected versions]:**
- Firefox Nightly 62.0a1

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following preference change in "about:config":
	- xpinstall.signatures.required = false
	- extensions.legacy.enabled = true
- Have the "DNS over HTTPS" add-on installed through "about:addons".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Go to "about:addons" page and remove the "DNS over HTTPS" add-on. 
3. Go to "about:config" and observe the "network.trr.experimentalRollout" pref.

**[Expected result]:**
- "network.trr.experimentalRollout" pref value is -1.

**[Actual result]:**
- "network.trr.experimentalRollout" pref value is 1.

**[Notes]:**
- "network.trr.experimentalRollout" pref value is -1 when disabling the add-on from the banner or from the "Study Description" page.
- This issue was logged after reading the conversation from #4 pull request, related to which value should the "network.trr.experimentalRollout" pref be changed into after disabling the study.
- Attached a screen recording of the issue:

![screen recording of the issue](https://user-images.githubusercontent.com/37875464/40240150-98e71c7c-5ac0-11e8-847d-244bc0145ef6.gif)

**Comment by jonathanKingston** [comment]
I have made this be a "uninstalled" state with the following change: https://github.com/jonathanKingston/http-dns/pull/4/commits/1e418ae6de9962b99ccbbdec75bccc3b442d284b

You should see a -2 in the pref, we might want to decide if we want to do the same for disable too.
