### ISSUE TITLE
[Enhancement] The DNS Studies banner should be more visible

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [jonathanKingston/http-dns#11]
[Affected versions]:
- Firefox Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".
- Have the "extensions.legacy.enabled" pref set to "true".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Install the "DNS Over HTTPS" experiment.
3. Observe the DNS Studies banner.

[Expected result]:
- The banner is visible and has some elements that are easy to be noticed (eg. the buttons have a different color).

[Actual result]:
- The banner lacks elements that stand out, therefore, it could be unnoticed by some users.

[Notes]:
- Here is a screenshot of the issue:
![dns studies banner](https://user-images.githubusercontent.com/31244235/40240659-bcd89916-5ac1-11e8-9bf7-672c4b3a0917.png)

**Comment by jonathanKingston** [comment]
Expected see #5
