### ISSUE TITLE
[Enhancement] The "Learn More" link from the banner should have a context menu

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [jonathanKingston/http-dns#12]
[Affected versions]:
- Firefox Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".
- Have the "extensions.legacy.enabled" pref set to "true".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Install the "DNS Over HTTPS" experiment.
3. Right click the "Learn More" link from the DNS Studies banner and observe the behavior.

[Expected result]:
- A context menu with specific options is displayed.

[Actual result]:
- Nothing happens.

[Notes]:
- Here is a screen recording of the issue:
![dns - enhancement](https://user-images.githubusercontent.com/31244235/40240724-ea09cd92-5ac1-11e8-933d-89aaa2765ee7.gif)

**Comment by jonathanKingston** [comment]
Default firefox behaviour for these banners. If you think this is an issue with Firefox perhaps it should be in Bugzilla. Thanks

**Comment by Softvision-CristinaBadescu** [comment]
Sure thing. We'll track it here: [bug 1463113](https://bugzilla.mozilla.org/show_bug.cgi?id=1463113).
