### ISSUE TITLE
"DNS Over HTTPS" ID's extension from "about:support" page is not "@shield.mozilla.org"

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#15]
[Affected versions]:
- Firefox Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false".
- Have the "extensions.legacy.enabled" pref set to "true".
- "DNS over HTTPS" add-on is already installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to "about:support" page.
3. Observe the extension of the study.

[Expected result]:
- "@shield.mozilla.org" extension is displayed.

[Actual result]:
- "@test.mozilla.org" extension is displayed.

[Notes]:
- Here is a screen shot of the issue: 

![extension](https://user-images.githubusercontent.com/26000308/40366862-d50fd32e-5de0-11e8-8ef9-95c2c6579953.png)

**Comment by jonathanKingston** [comment]
Fixed thanks

**Comment by SoftVision-CarmenFat** [comment]
Tested this on latest Nightly 62.0a1, using Windows 10 x64, Ubuntu 16.04 x64 and macOS 10.13. The ID is now changed to "@shield.mozilla.org" extension.
