### ISSUE TITLE
Add telemetry to measure opt outs better

### ISSUE THREAD

**Issue by jonathanKingston** [jonathanKingston/http-dns#20]
> @jtg567 - that's per normandy events - afaict the addon isn't sending shield telemetry so unfortunately I can't get a better estimate unless it is instrumented to measure opt-outs in some other way?

We will need to add Telemetry events for the next version to measure opt out rates.

**Comment by jtg567** [comment]
fyi https://github.com/mozilla/shield-studies-addon-utils#data-processing-pipelines

**Comment by jonathanKingston** [comment]
Resolved with the latest version
