### ISSUE TITLE
[Beta 63] DNS Over HTTPS V4 doesn't generate the banner nor the telemetry pings when installing the .zip file on Beta 63

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#22]
[Notes]:
- The experiment seems to be installed and enabled when checking the Add-ons Manager and "about:support" pages. 
- This issue is not reproducible on DevEdition 63.0b2. In this case, the banner and the pings are generated when following the same steps as below.

[Affected versions]:
- Firefox Beta 63.0b3
- DNS Over HTTPS V4 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "network.trr.uri" pref is set to "https://mozilla.cloudflare-dns.com/dns-query"
- DNS Over HTTPS V4 .zip is available ([link](https://github.com/jonathanKingston/http-dns/pull/21)). 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:debugging" page and install DNS Over HTTPS V4 as a temporary add-on.
3. Observe what happens next.
4. Navigate to "about:telemetry" -> "Archived ping data" section and observe if the experiment generated pings.

[Expected result]:
3. The banner is displayed on the bottom of the page.
4. "Enter" and "Installed" shield study pings are displayed.

[Actual result]:
3. Nothing happens, there is no UI indication related to the experiment.
4. There are no pings related to the shield study displayed.

[Additional Notes]:
- Added a screen recording with the issue:

![beta issue](https://user-images.githubusercontent.com/26000308/45095389-a29ef480-b126-11e8-9487-4d530a8e0345.gif)

**Comment by bagder** [comment]
`network.trr.mode` should also be set, to something like `2`.

But  you can also go to the networking prefs as it can be controlled with a UI now:

![doh-ui-preferences](https://user-images.githubusercontent.com/177011/45096040-dcb8c800-b11f-11e8-83cf-3ab8a67724bd.jpg)

**Comment by SoftVision-CarmenFat** [comment]
I've also set "network.trr.mode" pref to "2" value, but the result is the same as above.

**Comment by SoftVision-CarmenFat** [comment]
I don't know if this is helpful, but the following error is displayed in the Browser Console when trying to load the "manifest.json" file:
`TypeError: browser.study is undefined, can't access property "onEndStudy" of it`

![error](https://user-images.githubusercontent.com/26000308/45105105-3929e080-b13c-11e8-8b97-99e58c640e32.png)

**Comment by jonathanKingston** [comment]
This is because unsigned add-ons aren't permitted on beta, we need to get
it signed. Testing on dev edition skips these checks.

**Comment by SoftVision-CarmenFat** [comment]
@Jonathan, in this case, can you please provide us a signed .xpi of the study?
We'll continue testing the .zip file on Dev Edition, but we'd also like to take a look at the experiment on Beta channel, since we are planning to launch the study on it.

**Comment by jonathanKingston** [comment]
There is a signed addon attached to the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1485398

However this includes the 3 branches of the study which I just reduced to 2 but no other changes have happened since then.

**Comment by jonathanKingston** [comment]
Closing as I think this was just a signing issue only.
