### ISSUE TITLE
The experiment is wrongly displayed on the about:addons page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#28]
[Notes]:
- More info about this can be found [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1365349#c3).
- This issue can only be verified with a signed build. I'll leave it open until I have a signed build and verify after that.

[Affected versions]:
- Firefox Release 63.0.1 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The DNS Over HTTPS v5 is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to about:addons and observe the "Extensions" section.

[Expected result]:
- The addon is not displayed in the about:addons page.

[Actual result]:
- The addon is displayed.

[Additional Notes]:
- @mythmon says: "in order to have your add-on hidden in about:addons, you have to set "hidden": true in your manifest.json, if I recall correctly"
- I have attached a screenshot of the issue:
![dns](https://user-images.githubusercontent.com/26000308/48418651-7de67f00-e75e-11e8-8c8c-cabf8e4951bd.png)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest DNS Over HTTPS V5 (5.0.2-signed) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 16.04 x64.
