### ISSUE TITLE
There is no hover effect on banner buttons

### ISSUE THREAD

**Issue by poubina** [jonathanKingston/http-dns#29]
[Affected versions]:
Firefox Unbranded Release v63.0.1 and up

[Affected Platforms]:
Ubuntu Linux

[Prerequisites]:
DNS Over HTTPS V5.0.2 installed
The banner is displayed

[Steps to reproduce]:
1) Hover the "Disable DNS Studies" or "OK, Got it" button
2) Hover away the "Disable DNS Studies" or "OK, Got it" button

[Expected result]:
Hover effect should be displayed

[Actual result]:
No hover effect is displayed

[Notes]:
Screencast attached.

![nohover](https://user-images.githubusercontent.com/44272078/48574416-e1eb7d80-e8ed-11e8-9259-79628c8c4683.gif)

**Comment by jonathanKingston** [comment]
This is an issue with Firefox itself and not the extension. It's the agreed behaviour for those buttons and that code isn't modifying anything that Firefox is providing so we remain consistent.

I'm going to close this, thanks.
