### ISSUE TITLE
The tooltip string of the toolbar button is "__MSG_browserActionTitle__"

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#35]
[Affected versions]:
- Unbranded Firefox Release 66.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The DNS Over HTTPS v6 custom build is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Hover the DNS Over HTTPS toolbar button.
3. Observe the string from the tooltip.

[Expected result]:
- The "__ MSG_browserActionTitle __" string is displayed.

[Actual result]:
- The "DNS Over HTTPS" test string is displayed.

[Notes]:
- Attached is a screenshot of the issue:

![tooltip](https://user-images.githubusercontent.com/26000308/54751345-58bdbd80-4be3-11e9-900d-cca506dfbec5.png)

**Comment by jonathanKingston** [comment]
Can you retest please I don't think this was with a correctly built addon. I wasn't able to replicate.

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using httpdns@shield.mozilla.org-6.0.2-signed-testing.xpi on Windows 10 x64, Mac 10.13.6 and Ubuntu 16.04 using Firefox Unbranded Release Version 66.0.1, Build ID 20190322013140.
