### ISSUE TITLE
The DNS toolbar button has a different color than the other toolbar buttons

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [jonathanKingston/http-dns#36]
[Affected versions]:
- Firefox Release 66.0 Unbranded build

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The DNS Over HTTPS v6 custom build is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Observe the DNS toolbar button.

[Expected result]:
- The DNS toolbar button has the same color as the others. 

[Actual result]:
- The DNS toolbar button it's darker than the others.

[Additional Notes]:
- The issue is also reproducible with the Light or Dark theme.
- Attached is a screenshot the issue:
![issue](https://user-images.githubusercontent.com/19226534/54752119-9de2ef00-4be5-11e9-8c0a-445915fc12fe.png)

**Comment by Softvision-PatriciuPop** [comment]
After investigating using the httpdns@shield.mozilla.org-6.0.1-signed-testing.xpi it appears that for the default and light theme the values for the toolbar are the following:
![default theme](https://user-images.githubusercontent.com/40393891/55175449-030b8700-5188-11e9-9037-472ad2bc2f00.png)

And for the Dark theme:
![dark](https://user-images.githubusercontent.com/40393891/55175484-13236680-5188-11e9-81c0-3e6dd7990069.png)

**Comment by jonathanKingston** [comment]
Ah crud somehow the context-fill was dropped when updating the icon positioning. It's not possible to test an unsigned addon (I'm not even sure if the test signing will work either).

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using httpdns@shield.mozilla.org-6.0.3-signed-testing.xpi on Windows 10 x64, Mac 10.13.6 and Ubuntu 16.04 using Firefox Unbranded Release Version 66.0.2, Build ID 20190326175229.
