### ISSUE TITLE
The "Disable DNS Studies" button from the study's description page doesn't work

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#37]
[Affected versions]:
- Unbranded Firefox Release 66

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The DNS Over HTTPS v6 custom build is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the DNS Over HTTPS toolbar button.
3. Click the "Disable DNS Studies" button.
4. Observe what happens next.

[Expected result]:
- The experiment is uninstalled.

[Actual result]:
- The "DNS Over HTTPS" tab seems to be reloaded.

[Notes]:
- Attached is a screencast of the issue:

![disable studies](https://user-images.githubusercontent.com/26000308/54753508-dedd0280-4be9-11e9-920a-334483905c42.gif)

**Comment by jonathanKingston** [comment]
I'm not sure what this was using however I don't think this is with the signed addon. Would you be able to re-test please?

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using httpdns@shield.mozilla.org-6.0.2-signed-testing.xpi on Windows 10 x64, Mac 10.13.6 and Ubuntu 16.04 using Firefox Unbranded Release Version 66.0.1, Build ID 20190322013140.
