### ISSUE TITLE
Profiles without the Facebook login cookie generate telemetry probes that contain objects which have "-fb-" in the label key

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#38]
[Affected versions]:
- Unbranded Firefox Release 66

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The DNS Over HTTPS v6 custom build is installed.
- You never logged in your Facebook account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:telemetry" page and select the archived pings.
3. Select the "shield-study-addons" probe that contains the payload.
4. Observe the payload.

[Expected result]:
- The payload doesn't contain objects with "-fb-" in their label key.

[Actual result]:
- The payload contains objects with "-fb-" in their label key.

[Notes]:
- Attached is a screencast of the issue:

![fb label key](https://user-images.githubusercontent.com/26000308/54760907-b65d0480-4bf9-11e9-8eb0-46b5bb1459a1.gif)

**Comment by jonathanKingston** [comment]
As explained in my email this is the case. However the results are `[]` as they never were sent. This is the correct behaviour and the test script is wrong.
