### ISSUE TITLE
The "In this study" link from the experiment's description page redirects to a "Not Found" blog page

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [jonathanKingston/http-dns#40]
[Affected versions]:
- Firefox Unbranded Release Version 66.0.2, Build ID 20190326175229

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The xpinstall.signatures.required boolean pref is set with the false value.
- The extensions.legacy.enabled boolean pref is set with the true value.
- The xpinstall.signatures.dev-root boolean pref is set with the true value.
- The httpdns@shield.mozilla.org-6.0.3-signed-testing.xpi add-on is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and click the "DNS Over HTTPS" toolbar button.
2. Click the "In this study" link and observe the page.

[Expected result]:
- A blog article is opened on the same tab.

[Actual result]:
- A "Not Found" blog page is displayed on the same tab.

[Notes]:
- I have attached a screenshot of the issue:
![notfound](https://user-images.githubusercontent.com/40393891/55325442-c85a6500-548d-11e9-9f36-5aa5e24c403f.png)

**Comment by jonathanKingston** [comment]
This hasn't been published yet, however the short URL is redirectable after launch so will be fixed.

**Comment by Softvision-PatriciuPop** [comment]
This issue was fixed after the launch of the experiment.
