### ISSUE TITLE
Telemetry perf pings are no longer generated after restarting the browser with the PerfInterval pref modified to 60000 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#41]
[Affected versions]:
- Firefox Unbranded Release Version 66.0.2, Build ID 20190326175229

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The xpinstall.signatures.required boolean pref is set with the false value.
- The extensions.legacy.enabled boolean pref is set with the true value.
- The xpinstall.signatures.dev-root boolean pref is set with the true value.
- The httpdns@shield.mozilla.org-6.0.3-signed-testing.xpi add-on is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to "about:config" page.
3. Set the pref "network.trr.experimentalPerfInterval" to "60000" value (1 minute).
4. Restart the browser and wait for 1 minute.
5. Navigate to "about:telemetry" page and observe the archived pings.

[Expected result]:
- A new perf ping is generated after 1 minute.

[Actual result]:
- There is no perf ping generated.

[Notes]:
- No perf pings are generated if the users restart the browser right after the enrollment.

**Comment by jonathanKingston** [comment]
Should be fixed by: https://github.com/jonathanKingston/http-dns/pull/33/commits/a204acc7c3a5992fa2029d5f026557a1f18d2b1c

**Comment by Softvision-PatriciuPop** [comment]
I have verified that this issue is no longer reproducible using httpdns@shield.mozilla.org-6.0.4-signed-testing.xpi on Windows 10 x64, Mac 10.14.4 and Ubuntu 16.04 using Firefox Unbranded Release Version 66.0.2, Build ID 20190326175229.
