### ISSUE TITLE
[DNS over HTTPS experiment #7] The extension is not uninstalled after the study expires

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#43]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox unbranded Release 68 Build ID 20190705220548

[Prerequisites]:
- The "xpinstall.signatures.dev-root" boolen pref was created with the "true" value.
- The "doh_detection_logic@shield.mozilla.org-1.0.0-signed-testing.xpi" is installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to Control Panel->Clock and Region section.
3. Set the date for 8 days in the future.
4. Restart the Browser and navigate to "about:support" page.
5. Observe if the add-on is still displayed in the "Extensions" section.

[Expected result]:
- The "Detection Logic for DNS-over-HTTPS" is no longer displayed.

[Actual result]:
- The "Detection Logic for DNS-over-HTTPS" extensions is still displayed and enabled.

[Notes]:
- Please note that the "exit" and "expired" shield-study telemetry pings are generated in "about:telemetry" page.
- I have attached a screencast of the issue:

![expire](https://user-images.githubusercontent.com/26000308/61213006-7f60b080-a70c-11e9-83bb-7dabb270027a.gif)

**Comment by jonathanKingston** [comment]
https://github.com/jonathanKingston/http-dns/blob/master/src/background.js#L55 this is the line that needs changing.

**Comment by jonathanKingston** [comment]
The code is actually here: https://github.com/jonathanKingston/doh-heuristic/

**Comment by SoftVision-CarmenFat** [comment]
Tested this with the latest 1.0.1 DNS [build](https://bugzilla.mozilla.org/attachment.cgi?id=9078217) on Windows 10 x64, Ubuntu 18 x64 and macOS 101.14 and the add-on is now uninstalled after the expiration date.
