### ISSUE TITLE
The banner UI does not correspond to the UX documentation

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [jonathanKingston/http-dns#5]
[Affected versions]:
- Nightly 62.0a1
- DNS Over HTTPS

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to the "about:debugging" page.
2. Install the "DNS Over HTTPS" shield study.
2. Observe the "DNS Studies" banner from the bottom of the page.

[Expected result]:
- "Mozilla is working to improve [...] service operated by Cloudflare" black text is displayed on a light grey background.
- "Learn More" blue link is displayed at the end of the above text.
- "Disable DNS Studies" grey button is displayed on the right side of text and link.
- "OK, Got It" blue button is displayed at the right side of the banner.

[Actual result]:
- "OK, Got It" gray button is displayed at the right side of the banner.
- "Learn More" gray link is displayed at the end of the above text.

[Notes]:
- The banner design is presented in the following UX doc: https://docs.google.com/document/d/1gUG8J7tKuNoaHzZ3F28U425dQUUb1nch_Q_FLuMl8NE/edit
- Also, a question mark sign is displayed in front of the text from the banner.
- Here is a screen screenshot with this issue:
![dns - banner](https://user-images.githubusercontent.com/31244235/40181771-92bd92fa-59f2-11e8-889b-4db39cd378ea.png)

**Comment by jonathanKingston** [comment]
We agreed this wasn't a bug and instead is consistent with how Firefox looks. However I reverted the change to make it actually look like the expected, we can easily add it back in.
