### ISSUE TITLE
The experiment is still displayed as enabled in "about:addons" page after disabling it from the banner or the "Study Description" page

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [jonathanKingston/http-dns#7]
**[Affected versions]:**
- Firefox Nightly 62.0a1

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the "DNS over HTTPS" add-on installed from "about:debugging".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Disable DNS studies" button from the "DNS over HTTPS" banner displayed at the bottom of the page.
3. Go to "about:addons", "Extensions" section and observe the installed add-ons. 

**[Expected result]:**
- "DNS over HTTPS" add-on is removed.

**[Actual result]:**
- "DNS over HTTPS" add-on is displayed as enabled.

**[Notes]:**
- "DNS over HTTPS" add-on is also displayed as enabled in the "about:addons" page after you disable it from the "Study Description" page of the add-on. 
- Attached a screen recording of the issue:

![screen recording of the issue](https://user-images.githubusercontent.com/37875464/40182433-0d50a858-59f4-11e8-8e7e-49350e7f6ec8.gif)

**Comment by jonathanKingston** [comment]
This has been fixed in the latest changes thanks!

**Comment by Softvision-AndreeaCupsa** [comment]
I have tested this issue and is no longer reproducible on Mac, Win and Linux on Firefox Nightly 62.0a1.The add-on is no longer displayed in "about:addons" page after disabling the study from the banner and the study description page. Also, the network prefs are reseted to their default values.
