### ISSUE TITLE
Buttons from the banner and study description page don't display any hover effect 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#9]
[Affected Versions]:
- Nightly 62.0a1

[Affected Platforms]:
- Windows 10 x64
- Ubuntu 16.04 x64 
- macOS 10.13

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Install the DNS Over HTTPS experiment.
3. Hover the elements from the banner and observe the behavior.
4. Click the "Learn more" link and hover the "Disable DNS Studies" button from Description page and observe the behavior.

[Expected result]:
3. The buttons enter in hover state (getting highlighted).
4. The button enters in hover state (getting highlighted).

[Actual result]:
3. Nothing happens, the buttons don't enter in hover state.
4. Nothing happens, the button doesn't enter in hover state.

[Notes]:
- Here is a screen recording of the issue: https://tinyurl.com/ybrajhmp

**Comment by jonathanKingston** [comment]
The description page I have fixed in the latest changes, however we don't have an effect for that in Firefox. I don't think we should change the default behaviour of the banner.
